### ISSUE TITLE
Inheritance - go_to_definition support, parenting in general

### ISSUE THREAD

**Issue by Ariaks** [GameMakerDiscord/gml-tools-langserver#12]
self explanatory! would be awesome to have these features ;)

**Comment by sanbox-irl** [comment]
Lacking parenting in general.

Add to the indexer: parent of each object if object exists. Ascend upwards as far as we can.

Add to the parser: check for event_inherited(); Check for speed difference between semantics and simple `includes` on fullTextDocument. Prefer latter if speed is close -- so `var event_inherited()` still functions for type support.

Go to definition -- add special case -- go straight to the lowest parented event.

**Comment by sanbox-irl** [comment]
See https://github.com/GameMakerDiscord/gml-tools-langserver/issues/17 which has the same problem.
